/* GENERATED by scripts/build-flake-textures.mjs — do not edit by hand. */

/** Fallback ground, shown only if a texture fails to load. Sampled per blend. */
export const flakeBaseColors = {
  'basalt': '#5d5c65',
  'cabin-fever': '#7f7c77',
  'carbon': '#222023',
  'coyote': '#817e7a',
  'creekbed': '#827c72',
  'daredevil': '#4a4143',
  'dolerite': '#514b4c',
  'dovetail': '#7c7875',
  'garnet': '#51433e',
  'gravel': '#7b7c7d',
  'lanai-grey': '#68696d',
  'madras': '#777069',
  'nightfall': '#4f4f4c',
  'obsidian': '#60534b',
  'outback': '#816f61',
  'portobello': '#473d36',
  'pumice': '#786d6b',
  'rocky-arrow': '#8b8a88',
  'sable': '#736157',
  'safari': '#7c6a5a',
  'schist': '#929093',
  'shoreline': '#8f8777',
  'stargazer': '#848484',
  'stone-wash': '#6f6d6c',
  'stonehenge': '#7f8080',
  'stony-creek': '#8d8b88',
  'tidal-wave': '#848787',
} as const

export type TexturedBlendSlug = keyof typeof flakeBaseColors

/** Seamless installed-floor material, quilted from the blend's real sample.
 *  2048px tile ≈ 1.71ft of slab. */
export const flakeTexture = (slug: string) => `/images/flake-textures/${slug}.webp`

export const hasTexture = (slug: string): slug is TexturedBlendSlug =>
  Object.prototype.hasOwnProperty.call(flakeBaseColors, slug)
