/* GENERATED by scripts/build-flake-textures.mjs — do not edit by hand. */

/** The pigmented base coat showing between chips, sampled from each blend. */
export const flakeBaseColors = {
  'basalt': '#3d3c42',
  'cabin-fever': '#605e5a',
  'carbon': '#121212',
  'coyote': '#64625f',
  'creekbed': '#5c5952',
  'daredevil': '#181717',
  'dolerite': '#333030',
  'dovetail': '#575453',
  'garnet': '#362c28',
  'gravel': '#595a5b',
  'lanai-grey': '#47474a',
  'madras': '#4f4a45',
  'nightfall': '#383835',
  'obsidian': '#403730',
  'outback': '#5f5246',
  'portobello': '#28231e',
  'pumice': '#554d4a',
  'rocky-arrow': '#61605f',
  'sable': '#50443c',
  'safari': '#594b3f',
  'schist': '#666567',
  'shoreline': '#676256',
  'stargazer': '#5b5b5b',
  'stone-wash': '#4e4d4b',
  'stonehenge': '#575858',
  'stony-creek': '#605f5d',
  'tidal-wave': '#636362',
} as const

export type TexturedBlendSlug = keyof typeof flakeBaseColors

/** Seamless floor texture for a blend. 512px tile standing in for 4ft of slab. */
export const flakeTexture = (slug: string) => `/images/flake-textures/${slug}.webp`

export const hasTexture = (slug: string): slug is TexturedBlendSlug =>
  Object.prototype.hasOwnProperty.call(flakeBaseColors, slug)
