/* GENERATED by scripts/build-installed-previews.mjs — do not edit by hand. */

/*
  Pre-rendered installed-floor previews, one per blend.

  These are FLAT IMAGES, composited offline onto the one locked master
  photograph. The browser does not assemble a floor; it swaps an <img>. Any of
  them can be replaced with a photograph of a real finished floor by dropping
  the file in and leaving everything else alone.
*/

const WIDTHS = [1536, 1152, 768] as const

/*
  Two lighting states, both pre-rendered.

  An earlier dim state was reported as an almost-black floor with white discs on
  it. Neither fault was the dim state's own: the discs were the light field
  being allowed to run to 1.9x, which amplified the garage door's real
  reflections until they read as spotlights, and the darkness was an exposure
  picked by feel. Both were measured and fixed before this came back — see
  DIM_EXPOSURE and LIGHT_MAX in build-installed-previews.mjs.
*/
export type InstalledLighting = 'bright' | 'one-bulb'

/** Blends that have a rendered preview. */
export const installedPreviewSlugs = [
  'basalt',
  'cabin-fever',
  'carbon',
  'coyote',
  'creekbed',
  'daredevil',
  'dolerite',
  'dovetail',
  'garnet',
  'gravel',
  'lanai-grey',
  'madras',
  'nightfall',
  'obsidian',
  'outback',
  'portobello',
  'pumice',
  'rocky-arrow',
  'sable',
  'safari',
  'schist',
  'shoreline',
  'stargazer',
  'stone-wash',
  'stonehenge',
  'stony-creek',
  'tidal-wave',
] as const

export type InstalledPreviewSlug = (typeof installedPreviewSlugs)[number]

export const hasInstalledPreview = (slug: string): slug is InstalledPreviewSlug =>
  (installedPreviewSlugs as readonly string[]).includes(slug)

/** Largest rendition — use as the `src` fallback. */
export const installedPreview = (slug: string, lighting: InstalledLighting = 'bright') =>
  `/floor-previews/${slug}-${lighting}-1536.webp`

/** Responsive set, so a phone never downloads the desktop rendition. */
export const installedPreviewSrcSet = (slug: string, lighting: InstalledLighting = 'bright') =>
  WIDTHS.map((w) => `/floor-previews/${slug}-${lighting}-${w}.webp ${w}w`).join(', ')

/** Natural size of the master, so the browser can reserve the box. */
export const INSTALLED_PREVIEW_SIZE = { width: 1536, height: 1024 } as const
