/* GENERATED by scripts/build-installed-previews.mjs — do not edit by hand. */

/*
  Pre-rendered installed-floor previews, one per blend.

  These are FLAT IMAGES, composited offline onto the one locked master
  photograph. The browser does not assemble a floor; it swaps an <img>. Any of
  them can be replaced with a photograph of a real finished floor by dropping
  the file in and leaving everything else alone.
*/

const WIDTHS = [1536, 1152, 768] as const

/*
  There is no lighting parameter. A dim "one bulb" rendition used to exist
  alongside this and was what the floor-is-nearly-black report was actually
  about: it put the floor's median at 76 against 146 lit, and the garage door's
  reflections then stood 1.45x above that dark field, reading as white discs on
  a black surface.

  Bringing the mode back means re-introducing the argument here and in
  build-installed-previews.mjs — deliberately more than flipping a flag, so it
  cannot come back without someone looking at the numbers again.
*/

/** Blends that have a rendered preview. */
export const installedPreviewSlugs = [
  'basalt',
  'cabin-fever',
  'carbon',
  'coyote',
  'creekbed',
  'daredevil',
  'dolerite',
  'dovetail',
  'garnet',
  'gravel',
  'lanai-grey',
  'madras',
  'nightfall',
  'obsidian',
  'outback',
  'portobello',
  'pumice',
  'rocky-arrow',
  'sable',
  'safari',
  'schist',
  'shoreline',
  'stargazer',
  'stone-wash',
  'stonehenge',
  'stony-creek',
  'tidal-wave',
] as const

export type InstalledPreviewSlug = (typeof installedPreviewSlugs)[number]

export const hasInstalledPreview = (slug: string): slug is InstalledPreviewSlug =>
  (installedPreviewSlugs as readonly string[]).includes(slug)

/** Largest rendition — use as the `src` fallback. */
export const installedPreview = (slug: string) => `/floor-previews/${slug}-1536.webp`

/** Responsive set, so a phone never downloads the desktop rendition. */
export const installedPreviewSrcSet = (slug: string) =>
  WIDTHS.map((w) => `/floor-previews/${slug}-${w}.webp ${w}w`).join(', ')

/** Natural size of the master, so the browser can reserve the box. */
export const INSTALLED_PREVIEW_SIZE = { width: 1536, height: 1024 } as const
