import { allSitemapPaths, absoluteUrl } from '@/lib/sitemaps'
import { site } from '@/lib/site'

/*
  ============================================================================
  INDEXNOW
  ============================================================================

  IndexNow is a push protocol: instead of waiting to be crawled, the site tells
  participating engines "these URLs changed, come and look". Bing and Yandex
  consume it directly, and Seznam and Naver participate — submitting to any one
  endpoint shares the notification with all participants, so one call is enough.

  GOOGLE DOES NOT PARTICIPATE. This is worth being clear about rather than
  quietly implying otherwise: IndexNow does nothing for Google rankings or
  Google crawl scheduling. Google discovery still happens through the sitemap
  index and internal linking. What this buys is materially faster pickup on
  Bing, which also feeds ChatGPT search results — and the effort is one HTTP
  POST, so the trade is worth making even though the largest engine ignores it.

  THE KEY IS PUBLIC BY DESIGN. It is served at /<key>.txt and is how the
  protocol proves that whoever is submitting URLs controls the host. It is not a
  secret and must not be treated as one — putting it in an environment variable
  would be security theatre, because the value is readable by anyone who fetches
  the text file. What it must never be is a key belonging to someone else.
*/

/*
  MUST match the filename and contents of the file in public/.

  The key is served as a plain static file — public/<key>.txt — rather than
  generated by a route handler. A route would avoid having the value in two
  places, but the only way to do that at the site root is a top-level dynamic
  segment (app/[key]/route.ts), which then sits in front of every unmatched
  root path on a site that has fifteen real root-level pages. Not worth it to
  de-duplicate one constant.

  The duplication is instead guarded: scripts/indexnow-ping.mjs refuses to
  submit if public/<key>.txt is missing or its contents disagree with this
  value. That catches the actual failure mode — rotating the key in one place
  and not the other, which produces a 403 from the API for a reason that has
  nothing to do with the URLs submitted and is genuinely hard to diagnose.
*/
export const INDEXNOW_KEY = '3dd6dd142673d358cdeb01ac013c1724'

/** Where the key file must be reachable for a submission to be accepted. */
export const INDEXNOW_KEY_PATH = `/${INDEXNOW_KEY}.txt`

/*
  api.indexnow.org fans the submission out to every participating engine, so
  there is no reason to POST to bing.com and yandex.com separately.
*/
const ENDPOINT = 'https://api.indexnow.org/indexnow'

/** Host without scheme, which is the field name the protocol uses. */
const host = () => new URL(site.canonical).host

export type IndexNowResult = {
  ok: boolean
  status: number
  submitted: number
  /* Present when the call failed, for logging. Never surfaced to a visitor. */
  detail?: string
}

/**
 * Notifies IndexNow that a set of URLs has changed.
 *
 * Accepts paths (`/pricing/`) or absolute URLs and normalises to absolute,
 * because the protocol rejects a payload whose URLs are not all on the declared
 * host — a single relative path fails the whole batch.
 *
 * NEVER THROWS. A failed search-engine ping is not a reason for a deploy or a
 * request to fail, so every error path resolves to `ok: false` and is logged.
 * The caller decides whether to care.
 */
export async function submitToIndexNow(urls: readonly string[]): Promise<IndexNowResult> {
  const urlList = [...new Set(urls.map((u) => (u.startsWith('http') ? u : absoluteUrl(u))))]

  if (urlList.length === 0) {
    return { ok: true, status: 200, submitted: 0, detail: 'Nothing to submit.' }
  }

  /*
    The documented cap is 10,000 URLs per request. This site has well under 50,
    so the slice is a guard against a future bulk caller rather than a live
    concern — but a batch over the limit is rejected entirely, so it is worth
    the one line.
  */
  const batch = urlList.slice(0, 10_000)

  try {
    const response = await fetch(ENDPOINT, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json; charset=utf-8' },
      body: JSON.stringify({
        host: host(),
        key: INDEXNOW_KEY,
        keyLocation: `${site.canonical}${INDEXNOW_KEY_PATH}`,
        urlList: batch,
      }),
      /*
        A search-engine ping must not hang a deploy step or a request. 10s is
        generous for a single POST and bounded.
      */
      signal: AbortSignal.timeout(10_000),
    })

    /*
      200 accepted, 202 accepted-pending-key-validation. Both are successes.
      Anything else is worth seeing in the log: 400 malformed, 403 key not
      valid at keyLocation, 422 URLs do not match the declared host, 429 too
      many requests.
    */
    const ok = response.status === 200 || response.status === 202

    return {
      ok,
      status: response.status,
      submitted: batch.length,
      detail: ok ? undefined : await response.text().catch(() => 'no body'),
    }
  } catch (error) {
    return {
      ok: false,
      status: 0,
      submitted: 0,
      detail: error instanceof Error ? error.message : String(error),
    }
  }
}

/**
 * Submits every canonical indexable URL on the site.
 *
 * Derived from the same grouped registries the sitemap index is built from, so
 * a redirected or retired URL cannot be pushed — if it is not in the sitemap it
 * is not submitted here either.
 */
export function submitAllUrls(): Promise<IndexNowResult> {
  return submitToIndexNow(allSitemapPaths())
}
