import { site } from '@/lib/site'

/*
  Shared appointment-slot logic for the in-site scheduler.

  This is the scheduling counterpart to lib/leads.ts: the client picker and the
  server action both import it, so the slots a customer can SEE and the slots
  the server will ACCEPT are generated by the same code and cannot drift apart.
  Nothing here is server-only — it is pure date math with no secrets — so it is
  safe to run in the browser.

  TIME ZONE: the business is in Houston, so every slot is a civil time in
  America/Chicago. Slot ids are civil strings ("2026-09-24T08:00"), which are
  timezone-independent, so a slot means the same wall-clock time regardless of
  where the visitor's browser thinks it is. The absolute instant is derived from
  the civil time at send/validate, which is why DST is handled by Intl rather
  than a hardcoded offset.
*/

const TIME_ZONE = 'America/Chicago'

/*
  Inspection windows offered to customers. Two-hour arrival windows rather than
  exact times, because this is a scoping visit the crew routes around other
  jobs, not a fixed appointment. A window is only offered on a given day when it
  fits entirely inside that day's opening hours (see site.hours).
*/
const WINDOWS = [
  { start: '08:00', end: '10:00', label: '8:00 – 10:00 AM' },
  { start: '10:00', end: '12:00', label: '10:00 AM – 12:00 PM' },
  { start: '13:00', end: '15:00', label: '1:00 – 3:00 PM' },
  { start: '15:00', end: '17:00', label: '3:00 – 5:00 PM' },
  { start: '17:00', end: '19:00', label: '5:00 – 7:00 PM' },
] as const

/* How far ahead to offer, and the minimum notice before the earliest window. */
const MAX_OPEN_DAYS = 8
const MIN_LEAD_MS = 2 * 60 * 60 * 1000
const SLOT_ID_RE = /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})$/

export type ScheduleSlot = { id: string; label: string; at: string }
export type ScheduleDay = { dateId: string; weekday: string; dayLabel: string; slots: ScheduleSlot[] }

/*
  Opening hours keyed by weekday name, derived from the single source of truth
  in lib/site.ts. A day whose `opens` is null is closed and never produces
  slots. Deriving this (rather than re-listing hours here) means changing the
  footer hours also changes what the scheduler offers, with no second edit.
*/
const HOURS_BY_WEEKDAY: Record<string, { opens: string; closes: string } | null> = (() => {
  const map: Record<string, { opens: string; closes: string } | null> = {}
  for (const entry of site.hours) {
    for (const day of entry.dayOfWeek) {
      map[day] = entry.opens && entry.closes ? { opens: entry.opens, closes: entry.closes } : null
    }
  }
  return map
})()

/* Milliseconds America/Chicago is offset from UTC at a given instant (DST-aware). */
function tzOffsetMs(date: Date): number {
  const dtf = new Intl.DateTimeFormat('en-US', {
    timeZone: TIME_ZONE,
    hourCycle: 'h23',
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
  })
  const m: Record<string, number> = {}
  for (const p of dtf.formatToParts(date)) if (p.type !== 'literal') m[p.type] = Number(p.value)
  const asUTC = Date.UTC(m.year, m.month - 1, m.day, m.hour, m.minute, m.second)
  return asUTC - date.getTime()
}

/* A Houston civil date+time → the exact UTC instant it refers to. */
function houstonCivilToInstant(y: number, mo: number, d: number, h: number, mi: number): Date {
  const guess = Date.UTC(y, mo - 1, d, h, mi)
  return new Date(guess - tzOffsetMs(new Date(guess)))
}

/* Weekday of a civil calendar date, computed timezone-neutrally at civil noon. */
function weekdayOf(y: number, mo: number, d: number): string {
  return new Date(Date.UTC(y, mo - 1, d, 12)).toLocaleDateString('en-US', {
    weekday: 'long',
    timeZone: 'UTC',
  })
}

function dayLabelOf(y: number, mo: number, d: number): string {
  return new Date(Date.UTC(y, mo - 1, d, 12)).toLocaleDateString('en-US', {
    weekday: 'short',
    month: 'short',
    day: 'numeric',
    timeZone: 'UTC',
  })
}

/* Today's civil calendar date in Houston, as {y, mo, d}. */
function houstonToday(now: Date): { y: number; mo: number; d: number } {
  const dtf = new Intl.DateTimeFormat('en-US', {
    timeZone: TIME_ZONE,
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
  })
  const m: Record<string, number> = {}
  for (const p of dtf.formatToParts(now)) if (p.type !== 'literal') m[p.type] = Number(p.value)
  return { y: m.year, mo: m.month, d: m.day }
}

const pad = (n: number) => String(n).padStart(2, '0')

/*
  The list of bookable days, each with its available windows. Starts from today
  and walks forward until MAX_OPEN_DAYS *open* days have been collected, skipping
  closed days (Sundays) entirely and dropping any window that is already within
  MIN_LEAD_MS of `now` — so the earliest offer is always genuinely bookable.
*/
export function generateScheduleDays(now: Date = new Date()): ScheduleDay[] {
  const today = houstonToday(now)
  const anchor = Date.UTC(today.y, today.mo - 1, today.d)
  const cutoff = now.getTime() + MIN_LEAD_MS
  const days: ScheduleDay[] = []

  for (let offset = 0; offset < 30 && days.length < MAX_OPEN_DAYS; offset++) {
    const date = new Date(anchor + offset * 86_400_000)
    const y = date.getUTCFullYear()
    const mo = date.getUTCMonth() + 1
    const d = date.getUTCDate()

    const weekday = weekdayOf(y, mo, d)
    const hours = HOURS_BY_WEEKDAY[weekday]
    if (!hours) continue

    const dateId = `${y}-${pad(mo)}-${pad(d)}`
    const slots: ScheduleSlot[] = []

    for (const w of WINDOWS) {
      if (w.start < hours.opens || w.end > hours.closes) continue
      const [h, mi] = w.start.split(':').map(Number)
      const at = houstonCivilToInstant(y, mo, d, h, mi)
      if (at.getTime() < cutoff) continue
      slots.push({ id: `${dateId}T${w.start}`, label: w.label, at: at.toISOString() })
    }

    if (slots.length > 0) {
      days.push({ dateId, weekday, dayLabel: dayLabelOf(y, mo, d), slots })
    }
  }

  return days
}

export type ValidatedSlot = { at: Date; label: string; dayLabel: string; slotLabel: string }

/*
  Server-side validation of a slot id posted by the client.

  Rebuilds the slot from first principles rather than trusting the posted label:
  the id must be well-formed, land on an open weekday, match a real window that
  fits that day's hours, and still be in the future. Returns the authoritative
  label the server stores and emails, so a tampered client label cannot change
  what the business is told. Returns null for anything that fails.
*/
export function validateSlotId(id: string, now: Date = new Date()): ValidatedSlot | null {
  const match = SLOT_ID_RE.exec(id)
  if (!match) return null

  const [, ys, mos, ds, hs, mis] = match
  const y = Number(ys)
  const mo = Number(mos)
  const d = Number(ds)

  const window = WINDOWS.find((w) => w.start === `${hs}:${mis}`)
  if (!window) return null

  const weekday = weekdayOf(y, mo, d)
  const hours = HOURS_BY_WEEKDAY[weekday]
  if (!hours) return null
  if (window.start < hours.opens || window.end > hours.closes) return null

  const at = houstonCivilToInstant(y, mo, Number(d), Number(hs), Number(mis))
  /* Allow a small grace so a booking made right at the lead cutoff is not lost. */
  if (at.getTime() < now.getTime() - 60 * 60 * 1000) return null
  if (at.getTime() > now.getTime() + 60 * 86_400_000) return null

  const dayLabel = new Date(Date.UTC(y, mo - 1, d, 12)).toLocaleDateString('en-US', {
    weekday: 'long',
    month: 'long',
    day: 'numeric',
    timeZone: 'UTC',
  })

  return { at, label: `${dayLabel} · ${window.label} (CT)`, dayLabel, slotLabel: window.label }
}
